### ISSUE TITLE
Host Release Version Packages on nuget.org

### ISSUE THREAD

**Issue by jjr2000** [jrsearles/Elmah.AspNetCore#31]
The amount of effort that you are putting in to Modernising and Securing the (as far as I can tell) abandoned ElmahCore library is fantastic! Great work.

However this version can't realistically be used in any for of a production ready development pipeline until Sem Ver versioned release packages of it start being released to [nuget.org](https://www.nuget.org/), do you have a timeline for when builds stop being in the preview stage?

**Comment by jrsearles** [comment]
Hi and thanks for the feedback. I am still testing and making sure the app is label before bumping to a stable release. I'm hoping to have an initial stable release out within a week or two.

**Comment by jrsearles** [comment]
OK - packages are released as 1.0.0. Let me know if you run into any issues.
